In [7]:
#Импортировать модули sys numpy pandas
import sys
import numpy as np
import pandas as pd

In [32]:
#Создать объект pandas Series из листа, объекта NumPy, и словаря
ser1 = pd.Series([1,4,8,16,32])
print(ser1)
ser2 = pd.Series(np.arange(5))
print(ser2)
ser3 = pd.Series({"a":1, "b":2, "c":3})
print(ser3)

0     1
1     4
2     8
3    16
4    32
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int32
a    1
b    2
c    3
dtype: int64


In [22]:
#Преобразовать объект Series в DataFrame
pd.DataFrame(ser3)

0
a  1
b  2
c  3

In [34]:
#объединить несколько объектов Series в Dataframe
pd.DataFrame({'f':ser1.values, 's':ser2.values})

f  s
0   1  0
1   4  1
2   8  2
3  16  3
4  32  4

In [35]:
#Присвоить имя индексу объекта Series
ser1.rename_axis('index')

index
0     1
1     4
2     8
3    16
4    32
dtype: int64

In [38]:
#Получить элементы объекта Series A, которых нет в объекте Series B
#возвратить вместе с индексами
ans = ser1[~ser1.isin(ser2)]

In [40]:
#возвратить значения
print(ans.values)

[ 8 16 32]


In [42]:
#Получить не пересекающиеся элементы в двух объектах Series
np.setxor1d(ser1, ser2, assume_unique=False)

array([ 0,  2,  3,  8, 16, 32], dtype=int64)

In [51]:
#получить объединенный Series без повтороений
union = pd.Series(np.union1d(ser1, ser2))
print(union)

0     0
1     1
2     2
3     3
4     4
5     8
6    16
7    32
dtype: int64


In [52]:
#получить пересекающиеся данные
intersect = pd.Series(np.intersect1d(ser1, ser2))
print(intersect)

0    1
1    4
dtype: int64


In [53]:
#отобрать все данные, кроме пересекающихся
ans = union[~union.isin(intersect)]
print(ans)

0     0
2     2
3     3
5     8
6    16
7    32
dtype: int64


In [54]:
print(ans.values)

[ 0  2  3  8 16 32]
