### Лабораторные №1,2 по NumPy

Выполнил:   Миронов С.В.

Группа:	    М8О-103М-20


In [2]:
#Импортировать NumPy под именем np
import numpy as np
import matplotlib.pyplot as plt
#Напечатать версию и конфигурацию
print(np.__version__)

1.18.1


In [3]:
#Создать вектор (одномерный массив) размера 10, заполненый нулями
np.zeros([10])
#Создать вектор размер 10, заполненный единицами
np.ones([10])
#Создать вектор размера 10, заполненный числом 2.5
np.full([10], 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [4]:
#Получить документацию о функции numpy.add из командной строки
help (np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [5]:
#Создать вектор заполненный нулями, но пятый элемент равен 1
m = np.zeros([10])
m[4] = 1
m

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
#Создать вектор со значениями от 10 до 49
np.arange(start=10, stop=50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#Развернуть вектор (первый становится последним)
m = np.arange(start=1, stop=10)
print(m)
print(m[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [8]:
#Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#Найти индексы ненулевых элементов в [1,2,0,0,4,0]
m=np.array([1,2,0,0,4,0])
print(np.where(m != 0))

(array([0, 1, 4], dtype=int64),)


In [10]:
#Создать массив 3x3x3 со случайными значениями
np.random.randint(1,100,[3,3,3])

array([[[73, 97, 68],
        [50, 83, 55],
        [56, 11, 89]],

       [[81, 75, 13],
        [10, 48, 12],
        [39, 52, 33]],

       [[25, 96, 95],
        [55, 36, 77],
        [ 9, 11, 70]]])

In [11]:
#Создать массив 10x10 со случайными значениями, найти минимум и максимум
m=np.random.randint(1,1000,[10,10])
print(m.min(), m.max())

10 981


In [12]:
#Создать случайный вектор размера 30 и найти среднее значение всех элементов
m=np.random.randint(1,1000,[30])
print(m.mean())

451.1333333333333


In [13]:
#Создать матрицу с 0 внутри, и 1 на границах
m=np.ones([5,5])
m[1:-1:1, 1:-1:1]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#Выяснить результат следующих выражений
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


In [15]:
#Создать 5x5 матрицу с 1,2,3,4 под диагональю
m=np.zeros([5,5])
for i in range(m.shape[0]):
    m[i,i-1]=i
m

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [16]:
#Создать 8x8 матрицу и заполнить её в шахматном порядке
m=np.zeros([8,8])
for i in range(m.shape[0]):
    for i1 in range(m.shape[1]):
        m[i,i1]=(i1+i)%2
m

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [17]:
#Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [18]:
#Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
m = np.tile(A=np.array([[1,0], [0,1]]), reps=[4,4])
m

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [19]:
#Перемножить матрицы 5x3 и 3x2
m1=np.ones([5,3])
m2=np.ones([3,2])
print(m1.dot(m2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [20]:
#Дан массив, поменять знак у элементов, значения которых между 3 и 8
m=np.random.randint(1,20,30)
cond= np.bitwise_and(m>3, m<8) 
m=np.where(cond, -m, m)
m

array([ 3, 14, 16, 19, 19, 10, -6, 15, 18,  8, -7,  1, 19,  3,  2, 17,  2,
       19, 16, 17,  3, -5, 13, 16, 14, 15, -7, 13, 13, 16])

In [21]:
#Создать 5x5 матрицу со значениями в строках от 0 до 4
m=np.zeros([5,5])
n=np.arange(5)
print(m+n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [22]:
#Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
m=np.linspace(0.1,1,10, endpoint=False)
m

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

In [23]:
#Отсортировать вектор
m=np.random.randint(1,100,20)
print(m)
print(sorted(m))

[78 16 44 91 10 23 58 54 29 74 15 33  6  8 54 42  5 65 84 97]
[5, 6, 8, 10, 15, 16, 23, 29, 33, 42, 44, 54, 54, 58, 65, 74, 78, 84, 91, 97]


In [24]:
#Проверить, одинаковы ли 2 numpy массива
m=np.array([1,2,3])
n=np.array([1,2,3])
print((m==n).all())

True


In [3]:
#Сделать массив неизменяемым
m = np.arange(10)
m.flags.writeable = False
m[0]=-1

ValueError: assignment destination is read-only

In [26]:
#Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
m = np.random.randint(1,5,(10,2))
X,Y = m[:,0], m[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[3.60555128 5.         4.47213595 2.23606798 4.47213595 3.60555128
 5.         3.16227766 2.82842712 2.82842712]
[0.98279372 0.64350111 0.46364761 0.46364761 0.46364761 0.5880026
 0.64350111 0.32175055 0.78539816 0.78539816]


In [27]:
#Заменить максимальный элемент на ноль
m=np.random.randint(1,10,10)
print(m)
m[m.argmax()]=0
print(m)

[2 8 6 8 3 2 7 2 7 6]
[2 0 6 8 3 2 7 2 7 6]


In [28]:
#Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

X = np.arange(4)
Y = np.random.randint(10,20,4)
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-0.05555556, -0.07142857, -0.09090909, -0.0625    ],
       [-0.05882353, -0.07692308, -0.1       , -0.06666667],
       [-0.0625    , -0.08333333, -0.11111111, -0.07142857],
       [-0.06666667, -0.09090909, -0.125     , -0.07692308]])

In [29]:
#Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
   print(str(dtype)+str(np.iinfo(dtype).min))
   print(str(dtype)+str(np.iinfo(dtype).max))
for dtype in [np.float32, np.float64]:
   print(str(dtype)+str(np.finfo(dtype).min))
   print(str(dtype)+str(np.finfo(dtype).max))
   print(str(dtype)+str(np.finfo(dtype).eps))

<class 'numpy.int8'>-128
<class 'numpy.int8'>127
<class 'numpy.int32'>-2147483648
<class 'numpy.int32'>2147483647
<class 'numpy.int64'>-9223372036854775808
<class 'numpy.int64'>9223372036854775807
<class 'numpy.float32'>-3.4028235e+38
<class 'numpy.float32'>3.4028235e+38
<class 'numpy.float32'>1.1920929e-07
<class 'numpy.float64'>-1.7976931348623157e+308
<class 'numpy.float64'>1.7976931348623157e+308
<class 'numpy.float64'>2.220446049250313e-16


In [30]:
#Найти ближайшее к заданному значению число в заданном массиве
m = np.arange(100)
n = np.random.randint(0,100)
index = (np.abs(m-n)).argmin()
print(m[index])

57


In [31]:
#Дан массив (100,2) координат, найти расстояние от каждой точки до каждой
import scipy.spatial
m = np.random.randint(1,100,(10,2))
D = scipy.spatial.distance.cdist(m,m)
print(D)

[[  0.          46.27094121  14.86606875  76.94153625  78.77182237
   65.          23.2594067  107.16809227  69.8140387   55.00909016]
 [ 46.27094121   0.          54.4242593   63.78871374  40.22437072
   29.73213749  58.24087911  73.430239    50.08991915  20.22374842]
 [ 14.86606875  54.4242593    0.          91.67878708  90.44335244
   77.00649323  35.35533906 120.24142381  84.05355436  66.61080993]
 [ 76.94153625  63.78871374  91.67878708   0.          44.59820624
   40.31128874  65.76473219  46.01086828  14.76482306  44.92215489]
 [ 78.77182237  40.22437072  90.44335244  44.59820624   0.
   13.92838828  80.8084154   33.61547263  31.06444913  23.85372088]
 [ 65.          29.73213749  77.00649323  40.31128874  13.92838828
    0.          67.08203932  44.40720662  25.55386468  10.63014581]
 [ 23.2594067   58.24087911  35.35533906  65.76473219  80.8084154
   67.08203932   0.         103.76897417  62.96824597  59.13543777]
 [107.16809227  73.430239   120.24142381  46.01086828  33.615472

In [56]:
#Преобразовать массив из float в int
m = np.arange(10, dtype=np.int32)
m = m.astype(np.float32)
m

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [5]:
#Каков эквивалент функции enumerate для numpy массивов?
m= np.arange(25).reshape(5,5)
for index, value in np.ndenumerate(m):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19
(4, 0) 20
(4, 1) 21
(4, 2) 22
(4, 3) 23
(4, 4) 24


In [15]:
#Сформировать 2D массив с распределением Гаусса

X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
G

array([[0.36787944, 0.53526143, 0.60653066, 0.53526143, 0.36787944],
       [0.53526143, 0.77880078, 0.8824969 , 0.77880078, 0.53526143],
       [0.60653066, 0.8824969 , 1.        , 0.8824969 , 0.60653066],
       [0.53526143, 0.77880078, 0.8824969 , 0.77880078, 0.53526143],
       [0.36787944, 0.53526143, 0.60653066, 0.53526143, 0.36787944]])

In [23]:
#Случайно расположить p элементов в 2D массив

num_of_elements=10
m = np.zeros((8,8))
np.put(m, np.random.choice(range(8*8), num_of_elements, replace=False), 1)
m

array([[1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
#Отнять среднее из каждой строки в матрице

X = np.random.randint(1,10, (5, 10))
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[1 4 4 6 7 8 8 5 3 9]
 [9 8 3 2 8 1 7 5 4 6]
 [7 8 1 2 2 6 9 9 4 5]
 [6 9 5 9 8 4 9 8 4 8]
 [8 7 4 7 2 9 6 4 9 4]]
[[-4.5 -1.5 -1.5  0.5  1.5  2.5  2.5 -0.5 -2.5  3.5]
 [ 3.7  2.7 -2.3 -3.3  2.7 -4.3  1.7 -0.3 -1.3  0.7]
 [ 1.7  2.7 -4.3 -3.3 -3.3  0.7  3.7  3.7 -1.3 -0.3]
 [-1.   2.  -2.   2.   1.  -3.   2.   1.  -3.   1. ]
 [ 2.   1.  -2.   1.  -4.   3.   0.  -2.   3.  -2. ]]


In [30]:
#Отсортировать матрицу по n-ому столбцу

m = np.random.randint(0,10,(3,3))
n = 1 
print(m)
print(m[m[:n].argsort()])

[[8 5 2]
 [6 4 8]
 [0 6 1]]
[[[0 6 1]
  [6 4 8]
  [8 5 2]]]


In [33]:
# Определить, есть ли в 2D массиве нулевые столбцы


m = np.random.randint(0,10,(5,10))
print((~m.any(axis=0)).any())

False


In [34]:
#Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)
Z = np.ones(10)
I = np.random.randint(0,len(Z),10)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4 1 5 8 6 9 3 1 3 4]
[1. 3. 1. 3. 3. 2. 2. 1. 2. 2.]


In [35]:
#Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

?

In [40]:
#Дан четырехмерный массив, посчитать сумму по последним двум осям
A = np.random.randint(0,10, (3,4,3,4))
print(A)
A= A.reshape(A.shape[:-2] + (-1,))
print(A)
s=A.sum(axis=-1)
print(s)

[[[[0 9 3 6]
   [4 7 2 9]
   [5 4 3 5]]

  [[6 2 0 2]
   [5 8 9 6]
   [1 2 0 5]]

  [[1 1 1 2]
   [7 6 3 3]
   [9 2 4 7]]

  [[4 3 1 7]
   [1 0 9 0]
   [3 1 3 0]]]


 [[[2 3 0 1]
   [2 2 1 2]
   [6 9 3 7]]

  [[4 9 9 4]
   [9 2 0 0]
   [6 4 1 4]]

  [[3 2 8 1]
   [1 4 5 1]
   [0 4 4 1]]

  [[7 6 6 9]
   [1 5 4 0]
   [9 5 9 2]]]


 [[[2 2 7 2]
   [6 0 4 0]
   [2 3 4 7]]

  [[0 2 9 3]
   [6 4 8 4]
   [6 4 8 0]]

  [[7 4 7 4]
   [4 7 3 4]
   [5 6 5 9]]

  [[1 6 8 7]
   [3 9 0 3]
   [0 5 3 1]]]]
[[[0 9 3 6 4 7 2 9 5 4 3 5]
  [6 2 0 2 5 8 9 6 1 2 0 5]
  [1 1 1 2 7 6 3 3 9 2 4 7]
  [4 3 1 7 1 0 9 0 3 1 3 0]]

 [[2 3 0 1 2 2 1 2 6 9 3 7]
  [4 9 9 4 9 2 0 0 6 4 1 4]
  [3 2 8 1 1 4 5 1 0 4 4 1]
  [7 6 6 9 1 5 4 0 9 5 9 2]]

 [[2 2 7 2 6 0 4 0 2 3 4 7]
  [0 2 9 3 6 4 8 4 6 4 8 0]
  [7 4 7 4 4 7 3 4 5 6 5 9]
  [1 6 8 7 3 9 0 3 0 5 3 1]]]
[[57 46 46 32]
 [38 52 34 63]
 [39 54 65 46]]


In [ ]:
#Найти диагональные элементы произведения матриц


np.diag(np.dot(A, B))