### Лабораторная №3 по NumPy

Выполнил:   Миронов С.В.

Группа:	    М8О-103М-20


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

m = np.array([1, 2, 3, 4, 5])
m1= np.zeros(len(m)*4)
m1[::4]=m
m1

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

In [6]:
#Поменять 2 строки в матрице


m = np.arange(25).reshape(5,5)
m[[0]], m[[1]] = m[[1]], m[[0]]
m

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), 
# найти множество уникальных отрезков, составляющих все треугольники

?

In [9]:
#Дан массив C; создать массив A, что np.bincount(A) == C

C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(np.bincount(A))

[0 2 1 1 2 0 1]
[0 2 1 1 2 0 1]


In [10]:
#Посчитать среднее, используя плавающее окно

def moving_window(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_window(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [11]:
# Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]),
# каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))
from numpy.lib import stride_tricks

Z = np.arange(20)
M = stride_tricks.as_strided(Z, shape=(Z.size-2, 3), strides = (Z.itemsize, Z.itemsize))
M

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19]])

In [12]:
#Инвертировать булево значение, или поменять знак у числового массива без создания нового
M = np.arange(10)
np.negative(M, out=M)
M

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [16]:
#Посчитать ранг матрицы
M = np.random.randint(0,10,(10,10))
print(np.linalg.matrix_rank(M))

10


In [19]:
#Найти наиболее частое значение в массиве

M = np.random.randint(0,10,10)
print(np.bincount(M).argmax())

8


In [21]:
#Извлечь все смежные 3x3 блоки из 10x10 матрицы

Z = np.arange(100).reshape(10,10)
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[ 0  1  2]
   [10 11 12]
   [20 21 22]]

  [[ 1  2  3]
   [11 12 13]
   [21 22 23]]

  [[ 2  3  4]
   [12 13 14]
   [22 23 24]]

  [[ 3  4  5]
   [13 14 15]
   [23 24 25]]

  [[ 4  5  6]
   [14 15 16]
   [24 25 26]]

  [[ 5  6  7]
   [15 16 17]
   [25 26 27]]

  [[ 6  7  8]
   [16 17 18]
   [26 27 28]]

  [[ 7  8  9]
   [17 18 19]
   [27 28 29]]]


 [[[10 11 12]
   [20 21 22]
   [30 31 32]]

  [[11 12 13]
   [21 22 23]
   [31 32 33]]

  [[12 13 14]
   [22 23 24]
   [32 33 34]]

  [[13 14 15]
   [23 24 25]
   [33 34 35]]

  [[14 15 16]
   [24 25 26]
   [34 35 36]]

  [[15 16 17]
   [25 26 27]
   [35 36 37]]

  [[16 17 18]
   [26 27 28]
   [36 37 38]]

  [[17 18 19]
   [27 28 29]
   [37 38 39]]]


 [[[20 21 22]
   [30 31 32]
   [40 41 42]]

  [[21 22 23]
   [31 32 33]
   [41 42 43]]

  [[22 23 24]
   [32 33 34]
   [42 43 44]]

  [[23 24 25]
   [33 34 35]
   [43 44 45]]

  [[24 25 26]
   [34 35 36]
   [44 45 46]]

  [[25 26 27]
   [35 36 37]
   [45 46 47]]

  [[26 27 28]
   [36 37 38]


In [38]:
# Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). 
# Посчитать сумму p произведений матриц (результат имеет размерность (n,1))
p,n = 5, 3
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[15.],
       [15.],
       [15.]])

In [24]:
#Дан массив 16x16, посчитать сумму по блокам 4x4

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [25]:
#Найти n наибольших значений в массиве

Z = np.arange(10000)
print (Z[np.argpartition(-Z,10)[:10]])

[9992 9996 9993 9998 9991 9994 9995 9997 9999 9990]


In [40]:
# Даны 2 массива A (8x3) и B (2x2). 
# Найти строки в A, которые содержат элементы из каждой строки в B,
# независимо от порядка элементов в B


A = np.random.randint(0,5,(3,3))
print(A)
print()
B = np.random.randint(0,5,(2,2))
print(B)

C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[2 2 1]
 [0 4 1]
 [3 1 0]]

[[2 0]
 [0 0]]
[[[[ True False]
   [False False]]

  [[ True False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [ True  True]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False  True]
   [ True  True]]]]
[0 1 2]


In [39]:
#Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

Z = np.random.randint(0,2,(5,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print("Неравные значения:")
print(U)

[[1 1 1]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
Неравные значения:
[[1 1 0]]


In [42]:
#Преобразовать вектор чисел в матрицу бинарных представлений

I = np.array([0, 1, 2, 4, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [ ]:
#Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)